### ISSUE TITLE
question (other region)

### ISSUE THREAD

**Issue by fipoucat** [cordmaur/merge-downloader#1]
Hi Mauricio,

I am from West Africa and wonder if it is possible to use your Python package for other regions.
This is quite interesting and would kike to replicate it for West Africa.

Thank you

**Comment by cordmaur** [comment]
Hi @fipoucat , unfortunately this product is available only in South America. I suggest taking a look at CHIRPS or IMERGE for a global coverage.

**Comment by fipoucat** [comment]
Ok thank you
