### ISSUE TITLE
How to obtain the values of precipitation for only one cell of product?

### ISSUE THREAD

**Issue by pedrober31** [cordmaur/merge-downloader#4]
I'm trying obtain the values of precipitation for only cell of product. Fot this I use one point as base. But, I can't get the function that return only one cell in which the point is. Can you help me?

**Comment by cordmaur** [comment]
@pedrober31, If I understood correctly, you need the precipitation value for one pixel. Unfortunatelly, the GRIB files are not queryable and must be downloaded before data accessing. So you have 2 options. 
1- First option is to download the GRIBs using `merge-downloader` and open them on QGIS (image below).

![image](https://github.com/cordmaur/merge-downloader/assets/19617404/8fa730ae-14b6-4871-9819-ee98aa23d7bb)

2- Second option is to pass a `.geojson` file with a polygon representing just one pixel to `merge-downloader` using the `-s` (shape) flag, and it will create a series with just this pixel for you.

Hope it helps

**Comment by pedrober31** [comment]
Thank you!
